name: Notify Slack on PR Changes

on:
  pull_request:
    branches: ["main"]
    paths:
      - "public/locales/en/common.json"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get and format diff
        id: diff
        run: |
          # Get diff and remove diff markers
          git diff origin/${{ github.event.pull_request.base.ref }} -- public/locales/en/common.json |
          grep -E '^[+-][^+-]' |
          # Remove quotes and format with newlines
          sed 's/"//g' |
          sed 's/$/\\n/' |
          tr -d '\n' > formatted_diff.txt
          
          # Save to environment variable
          echo "FORMATTED_DIFF=$(cat formatted_diff.txt)" >> $GITHUB_ENV

      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🔔 JSON 변경 알림"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":magic_wand: *커밋한 사람:* ${{ steps.slack-mention.outputs.emails-mention }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Changes in common.json:*\n```${{ env.FORMATTED_DIFF }}```"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK