name: Notify Slack on PR Changes

# Controls when the workflow will run
on:
  pull_request:
    branches: ["main"]
    paths:
      - "public/locales/en/common.json"

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Send
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the diff of common.js
        id: get_diff
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} -- public/locales/en/common.json > diff.txt || true
          echo "DIFF<<EOF" >> $GITHUB_ENV
          cat diff.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Send notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks":
                [
                  {
                    "type": "section",
                    "text":
                      { "type": "mrkdwn", "text": "```${{ env.DIFF }}```" }
                  }
                ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
